# Form implementation generated from reading ui file 'XuanNiaoQuickTransfer.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import *
from PyQt5.QtWidgets import QMainWindow


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.atitleframe = QtWidgets.QFrame(self.centralwidget)
        self.atitleframe.setStyleSheet("background-color: rgba(122,211,255, 180)")
        self.atitleframe.setObjectName("atitleframe")
        self.titleLayout = QtWidgets.QHBoxLayout(self.atitleframe)
        self.titleLayout.setObjectName("titleLayout")
        self.label_titile = QtWidgets.QLabel(self.atitleframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titile.sizePolicy().hasHeightForWidth())
        self.label_titile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_titile.setFont(font)
        self.label_titile.setStyleSheet("background-color: rgba(255,255,255, 0)")
        self.label_titile.setObjectName("label_titile")
        self.titleLayout.addWidget(self.label_titile)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.titleLayout.addItem(spacerItem)
        self.pushButton_minimizeApp_2 = QtWidgets.QPushButton(self.atitleframe)
        self.pushButton_minimizeApp_2.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.pushButton_minimizeApp_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/icon/icon_settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_minimizeApp_2.setIcon(icon)
        self.pushButton_minimizeApp_2.setObjectName("pushButton_minimizeApp_2")
        self.titleLayout.addWidget(self.pushButton_minimizeApp_2)
        self.pushButton_minimizeApp = QtWidgets.QPushButton(self.atitleframe)
        self.pushButton_minimizeApp.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.pushButton_minimizeApp.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/icon/icon_minimize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_minimizeApp.setIcon(icon1)
        self.pushButton_minimizeApp.setObjectName("pushButton_minimizeApp")
        self.titleLayout.addWidget(self.pushButton_minimizeApp)
        self.pushButton_closeApp = QtWidgets.QPushButton(self.atitleframe)
        self.pushButton_closeApp.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.pushButton_closeApp.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image/icon/icon_close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_closeApp.setIcon(icon2)
        self.pushButton_closeApp.setObjectName("pushButton_closeApp")
        self.titleLayout.addWidget(self.pushButton_closeApp)
        self.verticalLayout_2.addWidget(self.atitleframe)
        self.mainframe = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainframe.sizePolicy().hasHeightForWidth())
        self.mainframe.setSizePolicy(sizePolicy)
        self.mainframe.setObjectName("mainframe")
        self.mainLayout = QtWidgets.QHBoxLayout(self.mainframe)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.chartframe = QtWidgets.QFrame(self.mainframe)
        self.chartframe.setObjectName("chartframe")
        self.chartlayout = QtWidgets.QVBoxLayout(self.chartframe)
        self.chartlayout.setContentsMargins(0, 0, 0, 0)
        self.chartlayout.setSpacing(0)
        self.chartlayout.setObjectName("chartlayout")
        self.scrollArea = QtWidgets.QScrollArea(self.chartframe)
        self.scrollArea.setStyleSheet("border:none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 420, 341))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chartbrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.chartbrowser.setStyleSheet("")
        self.chartbrowser.setObjectName("chartbrowser")
        self.horizontalLayout.addWidget(self.chartbrowser)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setAutoFillBackground(False)
        self.verticalScrollBar.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(240, 248, 255);\n"
"    width: 12px;\n"
"    margin: 10px 0 10px 0;\n"
" }\n"
"QScrollBar::handle:vertical {    \n"
"    background: rgb(100,211,255);\n"
"    min-height: 45px;\n"
"    border-radius: 5px\n"
" }\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: rgb(193,229,255);\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
" }\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(193,229,255);\n"
"    height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
" }\n"
"QScrollBar::up-arrow:vertical, \n"
"QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout.addWidget(self.verticalScrollBar)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.chartlayout.addWidget(self.scrollArea)
        self.medium_frame = QtWidgets.QFrame(self.chartframe)
        self.medium_frame.setStyleSheet("background-color: rgba(122,211,255, 180)")
        self.medium_frame.setObjectName("medium_frame")
        self.medium_layout = QtWidgets.QHBoxLayout(self.medium_frame)
        self.medium_layout.setContentsMargins(-1, -1, 9, -1)
        self.medium_layout.setObjectName("medium_layout")
        self.label_ipv4 = QtWidgets.QLabel(self.medium_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_ipv4.sizePolicy().hasHeightForWidth())
        self.label_ipv4.setSizePolicy(sizePolicy)
        self.label_ipv4.setStyleSheet("background-color: rgba(255,255,255, 0)")
        self.label_ipv4.setObjectName("label_ipv4")
        self.medium_layout.addWidget(self.label_ipv4)
        self.lineEdit_ipv4 = QtWidgets.QLineEdit(self.medium_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(110)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ipv4.sizePolicy().hasHeightForWidth())
        self.lineEdit_ipv4.setSizePolicy(sizePolicy)
        self.lineEdit_ipv4.setMinimumSize(QtCore.QSize(110, 20))
        self.lineEdit_ipv4.setStyleSheet("background-color: rgba(255,255,255, 240)")
        self.lineEdit_ipv4.setInputMask("")
        self.lineEdit_ipv4.setObjectName("lineEdit_ipv4")
        self.medium_layout.addWidget(self.lineEdit_ipv4)
        self.label_port = QtWidgets.QLabel(self.medium_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_port.sizePolicy().hasHeightForWidth())
        self.label_port.setSizePolicy(sizePolicy)
        self.label_port.setStyleSheet("background-color: rgba(255,255,255, 0)")
        self.label_port.setObjectName("label_port")
        self.medium_layout.addWidget(self.label_port)
        self.lineEdit_port = QtWidgets.QLineEdit(self.medium_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(45)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_port.sizePolicy().hasHeightForWidth())
        self.lineEdit_port.setSizePolicy(sizePolicy)
        self.lineEdit_port.setMinimumSize(QtCore.QSize(45, 20))
        self.lineEdit_port.setStyleSheet("background-color: rgba(255,255,255, 240)")
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.medium_layout.addWidget(self.lineEdit_port)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.medium_layout.addItem(spacerItem1)
        self.checkBox_connect = QtWidgets.QCheckBox(self.medium_frame)
        self.checkBox_connect.setStyleSheet("background-color: rgba(255,255,255, 0)")
        self.checkBox_connect.setChecked(True)
        self.checkBox_connect.setTristate(True)
        self.checkBox_connect.setObjectName("checkBox_connect")
        self.medium_layout.addWidget(self.checkBox_connect)
        self.chartlayout.addWidget(self.medium_frame)
        self.s_entry = QtWidgets.QLineEdit(self.chartframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_entry.sizePolicy().hasHeightForWidth())
        self.s_entry.setSizePolicy(sizePolicy)
        self.s_entry.setStyleSheet("border: none;")
        self.s_entry.setObjectName("s_entry")
        self.chartlayout.addWidget(self.s_entry)
        self.bottom_frame = QtWidgets.QFrame(self.chartframe)
        self.bottom_frame.setStyleSheet("background-color: rgba(255,255,255, 255)")
        self.bottom_frame.setObjectName("bottom_frame")
        self.bottom_layout = QtWidgets.QHBoxLayout(self.bottom_frame)
        self.bottom_layout.setContentsMargins(0, 0, 0, 0)
        self.bottom_layout.setSpacing(0)
        self.bottom_layout.setObjectName("bottom_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.bottom_layout.addItem(spacerItem2)
        self.pushButton_send = QtWidgets.QPushButton(self.bottom_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_send.sizePolicy().hasHeightForWidth())
        self.pushButton_send.setSizePolicy(sizePolicy)
        self.pushButton_send.setMinimumSize(QtCore.QSize(35, 0))
        self.pushButton_send.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.pushButton_send.setStyleSheet("QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    background-color: rgb(122,211,255);\n"
"    border: none;\n"
"    border-top-left-radius: 9px;\n"
"    border-top-right-radius: 9px;\n"
"    border-left: 15px solid transparent;\n"
"    border-right: 15px solid transparent;\n"
"    text-align: center;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(193,229,255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(245,245,255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_send.setDefault(False)
        self.pushButton_send.setFlat(True)
        self.pushButton_send.setObjectName("pushButton_send")
        self.bottom_layout.addWidget(self.pushButton_send)
        self.chartlayout.addWidget(self.bottom_frame)
        self.chartlayout.setStretch(0, 21)
        self.chartlayout.setStretch(1, 1)
        self.chartlayout.setStretch(2, 9)
        self.chartlayout.setStretch(3, 2)
        self.mainLayout.addWidget(self.chartframe)
        self.mainLayout.setStretch(0, 10)
        self.verticalLayout_2.addWidget(self.mainframe)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 24)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titile.setText(_translate("MainWindow", "玄鸟快传"))
        self.label_ipv4.setText(_translate("MainWindow", "电脑端ipv4:"))
        self.lineEdit_ipv4.setText(_translate("MainWindow", "192.168.0.0"))
        self.label_port.setText(_translate("MainWindow", "电脑端口号:"))
        self.lineEdit_port.setInputMask(_translate("MainWindow", "0000"))
        self.lineEdit_port.setText(_translate("MainWindow", "9999"))
        self.checkBox_connect.setText(_translate("MainWindow", "连接状态"))
        self.pushButton_send.setText(_translate("MainWindow", "发送"))
